"""Setup wizard helpers — config directory, .env writing, URL opening."""
from __future__ import annotations

import os
import sys
from pathlib import Path


def get_config_dir() -> Path:
    """Return the directory where .env should be written.

    Frozen (PyInstaller) builds use %APPDATA%\\TelegramSignalCopier so the
    config survives application updates.  Dev runs use the project root.
    """
    override = os.environ.get("TELEGRAM_SIGNAL_COPIER_HOME", "")
    if override:
        return Path(override)
    if getattr(sys, "frozen", False):
        return Path(os.environ.get("APPDATA", Path.home())) / "TelegramSignalCopier"
    # Dev mode — project root (two levels up from this file)
    return Path(__file__).resolve().parents[3]


def env_path() -> Path:
    d = get_config_dir()
    d.mkdir(parents=True, exist_ok=True)
    return d / ".env"


def write_env(fields: dict[str, str]) -> Path:
    path = env_path()
    lines: list[str] = [
        "# Generated by Telegram Signal Copier Setup Wizard",
        "",
        "# ── Telegram ────────────────────────────────────────────────────────────────",
        f"TELEGRAM_API_ID={fields.get('telegram_api_id', '')}",
        f"TELEGRAM_API_HASH={fields.get('telegram_api_hash', '')}",
        f"TELEGRAM_PHONE_NUMBER={fields.get('telegram_phone', '')}",
        "TELEGRAM_SESSION_NAME=telegram-signal-copier",
        "",
        "# ── Telegram Sources (group names; numeric IDs added after first discovery) ─",
        f"TELEGRAM_SOURCES={fields.get('telegram_sources', '')}",
        "",
        "# ── MT5 Account ─────────────────────────────────────────────────────────────",
        f"MT5_LOGIN={fields.get('mt5_login', '')}",
        f"MT5_PASSWORD={fields.get('mt5_password', '')}",
        f"MT5_SERVER={fields.get('mt5_server', '')}",
        f"MT5_SYMBOL_SUFFIX={fields.get('mt5_symbol_suffix', '')}",
        "",
        "# ── AI Provider (SambaNova free tier — swap key/URL for any OpenAI-compatible API)",
        f"OPENAI_API_KEY={fields.get('openai_api_key', '')}",
        "OPENAI_MODEL=Llama-4-Maverick-17B-128E-Instruct",
        "OPENAI_BASE_URL=https://api.sambanova.ai/v1",
        "",
        "# ── Trading Defaults ────────────────────────────────────────────────────────",
        f"DEFAULT_VOLUME={fields.get('default_volume', '0.01')}",
        "MINIMUM_CONFIDENCE=0.45",
        "APPROVAL_REQUIRED_BELOW=0.45",
        "ALLOWED_SYMBOLS=XAUUSD,EURUSD,GBPUSD,USDJPY,US30,NAS100,BTCUSD,ETHUSD,XAGUSD,USOIL,SPX500",
        "DRY_RUN=false",
        "SIGNAL_MAX_AGE_SECONDS=5400",
        "",
        "# ── Optional Overrides ──────────────────────────────────────────────────────",
        "# MT5_BRIDGE_DIR=C:\\Users\\YOU\\AppData\\Roaming\\MetaQuotes\\Terminal\\Common\\Files\\TelegramSignalCopierBridge",
        "# TELEGRAM_SIGNAL_COPIER_HOME=C:\\TelegramSignalCopierData",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def open_url(url: str) -> None:
    import webbrowser
    webbrowser.open(url)
