"""First-run setup wizard — collects Telegram + MT5 credentials and writes .env.

Launch via:  TelegramSignalCopier.exe setup
Or auto-launches when no .env is found on first run.
"""
from __future__ import annotations

import os
import subprocess
import sys
import threading
import tkinter as tk
from pathlib import Path
from tkinter import messagebox, ttk


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _get_config_dir() -> Path:
    """Return the directory where .env should be written.

    Frozen (PyInstaller) builds use %APPDATA%\\TelegramSignalCopier so the
    config survives application updates.  Dev runs use the project root.
    """
    override = os.environ.get("TELEGRAM_SIGNAL_COPIER_HOME", "")
    if override:
        return Path(override)
    if getattr(sys, "frozen", False):
        return Path(os.environ.get("APPDATA", Path.home())) / "TelegramSignalCopier"
    # Dev mode — project root (two levels up from this file)
    return Path(__file__).resolve().parents[3]


def _env_path() -> Path:
    d = _get_config_dir()
    d.mkdir(parents=True, exist_ok=True)
    return d / ".env"


def _write_env(fields: dict[str, str]) -> Path:
    path = _env_path()
    lines: list[str] = [
        "# Generated by Telegram Signal Copier Setup Wizard",
        "",
        "# ── Telegram ────────────────────────────────────────────────────────────────",
        f"TELEGRAM_API_ID={fields.get('telegram_api_id', '')}",
        f"TELEGRAM_API_HASH={fields.get('telegram_api_hash', '')}",
        f"TELEGRAM_PHONE_NUMBER={fields.get('telegram_phone', '')}",
        "TELEGRAM_SESSION_NAME=telegram-signal-copier",
        "",
        "# ── Telegram Sources (group names; numeric IDs added after first discovery) ─",
        f"TELEGRAM_SOURCES={fields.get('telegram_sources', '')}",
        "",
        "# ── MT5 Account ─────────────────────────────────────────────────────────────",
        f"MT5_LOGIN={fields.get('mt5_login', '')}",
        f"MT5_PASSWORD={fields.get('mt5_password', '')}",
        f"MT5_SERVER={fields.get('mt5_server', '')}",
        "",
        "# ── AI Provider (SambaNova free tier — swap key/URL for any OpenAI-compatible API)",
        f"OPENAI_API_KEY={fields.get('openai_api_key', '')}",
        "OPENAI_MODEL=Llama-4-Maverick-17B-128E-Instruct",
        "OPENAI_BASE_URL=https://api.sambanova.ai/v1",
        "",
        "# ── Trading Defaults ────────────────────────────────────────────────────────",
        f"DEFAULT_VOLUME={fields.get('default_volume', '0.01')}",
        "MINIMUM_CONFIDENCE=0.45",
        "APPROVAL_REQUIRED_BELOW=0.45",
        "ALLOWED_SYMBOLS=XAUUSD,EURUSD,GBPUSD,USDJPY,US30,NAS100,BTCUSD,ETHUSD,XAGUSD,USOIL,SPX500",
        "DRY_RUN=false",
        "SIGNAL_MAX_AGE_SECONDS=5400",
        "",
        "# ── Optional Overrides ──────────────────────────────────────────────────────",
        "# MT5_BRIDGE_DIR=C:\\Users\\YOU\\AppData\\Roaming\\MetaQuotes\\Terminal\\Common\\Files\\TelegramSignalCopierBridge",
        "# TELEGRAM_SIGNAL_COPIER_HOME=C:\\TelegramSignalCopierData",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Page base
# ---------------------------------------------------------------------------

class _Page(tk.Frame):
    """Base class for a wizard page."""

    title: str = ""
    subtitle: str = ""

    def __init__(self, parent: tk.Widget) -> None:
        super().__init__(parent, bg="#1e1e2e")

    def validate(self) -> str | None:
        """Return an error message if the page is invalid, else None."""
        return None

    def collect(self) -> dict[str, str]:
        """Return a dict of field values from this page."""
        return {}


# ---------------------------------------------------------------------------
# Pages
# ---------------------------------------------------------------------------

class WelcomePage(_Page):
    title = "Welcome to Telegram Signal Copier"
    subtitle = "This wizard will configure the app in a few quick steps."

    def __init__(self, parent: tk.Widget) -> None:
        super().__init__(parent)
        tk.Label(
            self,
            text="📋  What you'll need:",
            font=("Segoe UI", 11, "bold"),
            bg="#1e1e2e", fg="#cdd6f4",
        ).pack(anchor="w", pady=(20, 6), padx=30)

        items = [
            ("Telegram API credentials",
             "Get a free API ID + Hash from  my.telegram.org → 'API development tools'"),
            ("Your MT5 account details",
             "Account number, password and broker server name (e.g. Exness-MT5Real8)"),
            ("Telegram group names",
             "Names of the signal channels you want to copy trades from"),
            ("(Optional) AI API key",
             "SambaNova / Groq / OpenAI key for smarter signal parsing"),
        ]
        for heading, detail in items:
            row = tk.Frame(self, bg="#1e1e2e")
            row.pack(fill="x", padx=30, pady=3)
            tk.Label(row, text="✔  ", font=("Segoe UI", 10), bg="#1e1e2e", fg="#a6e3a1").pack(side="left")
            col = tk.Frame(row, bg="#1e1e2e")
            col.pack(side="left", fill="x")
            tk.Label(col, text=heading, font=("Segoe UI", 10, "bold"), bg="#1e1e2e", fg="#cdd6f4", anchor="w").pack(anchor="w")
            tk.Label(col, text=detail, font=("Segoe UI", 9), bg="#1e1e2e", fg="#6c7086", anchor="w", wraplength=440, justify="left").pack(anchor="w")

        tk.Label(
            self,
            text="Click  Next  to begin.",
            font=("Segoe UI", 10, "italic"),
            bg="#1e1e2e", fg="#89b4fa",
        ).pack(pady=20)


class TelegramPage(_Page):
    title = "Telegram Connection"
    subtitle = "Your Telegram API credentials and phone number."

    def __init__(self, parent: tk.Widget) -> None:
        super().__init__(parent)
        self._vars: dict[str, tk.StringVar] = {}
        fields = [
            ("Phone Number", "telegram_phone", "+1234567890", False,
             "International format, e.g. +447911123456"),
            ("API ID", "telegram_api_id", "", False,
             "From my.telegram.org → API development tools"),
            ("API Hash", "telegram_api_hash", "", False,
             "32-character string from my.telegram.org"),
        ]
        for label, key, placeholder, secret, hint in fields:
            self._add_field(label, key, placeholder, secret, hint)

        _link = tk.Label(
            self,
            text="Open my.telegram.org  ↗",
            font=("Segoe UI", 9, "underline"),
            bg="#1e1e2e", fg="#89b4fa",
            cursor="hand2",
        )
        _link.pack(anchor="w", padx=30, pady=(4, 0))
        _link.bind("<Button-1>", lambda _: _open_url("https://my.telegram.org/apps"))

    def _add_field(self, label: str, key: str, placeholder: str, secret: bool, hint: str) -> None:
        var = tk.StringVar(value=placeholder if placeholder and not placeholder.startswith("+") else "")
        if placeholder.startswith("+"):
            var.set(placeholder)
        self._vars[key] = var

        frame = tk.Frame(self, bg="#1e1e2e")
        frame.pack(fill="x", padx=30, pady=(10, 0))
        tk.Label(frame, text=label, font=("Segoe UI", 10, "bold"), bg="#1e1e2e", fg="#cdd6f4", anchor="w").pack(anchor="w")
        entry = tk.Entry(
            frame,
            textvariable=var,
            show="●" if secret else "",
            font=("Consolas", 10),
            bg="#313244", fg="#cdd6f4",
            insertbackground="#cdd6f4",
            relief="flat",
            bd=6,
            width=46,
        )
        entry.pack(fill="x", pady=2)
        if hint:
            tk.Label(frame, text=hint, font=("Segoe UI", 8), bg="#1e1e2e", fg="#6c7086", anchor="w").pack(anchor="w")

    def validate(self) -> str | None:
        phone = self._vars["telegram_phone"].get().strip()
        api_id = self._vars["telegram_api_id"].get().strip()
        api_hash = self._vars["telegram_api_hash"].get().strip()
        if not phone or not phone.startswith("+"):
            return "Phone number must start with + and country code (e.g. +44…)"
        if not api_id.isdigit():
            return "API ID must be a number from my.telegram.org"
        if len(api_hash) < 20:
            return "API Hash looks too short — copy the full 32-character string"
        return None

    def collect(self) -> dict[str, str]:
        return {k: v.get().strip() for k, v in self._vars.items()}


class MT5Page(_Page):
    title = "MT5 Account"
    subtitle = "Your MetaTrader 5 account credentials."

    def __init__(self, parent: tk.Widget) -> None:
        super().__init__(parent)
        self._vars: dict[str, tk.StringVar] = {}
        fields = [
            ("Account Login (number)", "mt5_login", "", False,
             "Your MT5 account number, e.g. 272489632"),
            ("Password", "mt5_password", "", True,
             "MT5 investor or master password"),
            ("Broker Server", "mt5_server", "", False,
             "Server name shown in MT5 login screen, e.g. Exness-MT5Real8"),
        ]
        for label, key, placeholder, secret, hint in fields:
            self._add_field(label, key, placeholder, secret, hint)

        tk.Label(
            self,
            text="⚠  MetaTrader 5 must be installed and running on this machine.\n"
                 "   Attach the TelegramSignalCopierEA Expert Advisor to any chart.",
            font=("Segoe UI", 9),
            bg="#1e1e2e", fg="#f38ba8",
            justify="left",
        ).pack(anchor="w", padx=30, pady=(18, 0))

    def _add_field(self, label: str, key: str, placeholder: str, secret: bool, hint: str) -> None:
        var = tk.StringVar()
        self._vars[key] = var
        frame = tk.Frame(self, bg="#1e1e2e")
        frame.pack(fill="x", padx=30, pady=(10, 0))
        tk.Label(frame, text=label, font=("Segoe UI", 10, "bold"), bg="#1e1e2e", fg="#cdd6f4", anchor="w").pack(anchor="w")
        entry = tk.Entry(
            frame,
            textvariable=var,
            show="●" if secret else "",
            font=("Consolas", 10),
            bg="#313244", fg="#cdd6f4",
            insertbackground="#cdd6f4",
            relief="flat",
            bd=6,
            width=46,
        )
        entry.pack(fill="x", pady=2)
        if hint:
            tk.Label(frame, text=hint, font=("Segoe UI", 8), bg="#1e1e2e", fg="#6c7086", anchor="w").pack(anchor="w")

    def validate(self) -> str | None:
        login_str = self._vars["mt5_login"].get().strip()
        password = self._vars["mt5_password"].get().strip()
        server = self._vars["mt5_server"].get().strip()
        if not login_str.isdigit():
            return "MT5 Account Login must be a number"
        if not server:
            return "Broker Server is required (check your MT5 login screen)"

        # Attempt to import MetaTrader5. If it fails (e.g. non-Windows platform or package not installed), skip verification
        try:
            import MetaTrader5 as mt5
        except ImportError:
            # Package not available (e.g. dev mode or different OS), skip verification
            return None

        # Display progress window
        progress = tk.Toplevel(self)
        progress.title("Verifying...")
        progress.configure(bg="#1e1e2e")
        progress.resizable(False, False)
        progress.transient(self)
        progress.grab_set()

        # Center progress window
        w, h = 320, 120
        parent_x = self.winfo_toplevel().winfo_x()
        parent_y = self.winfo_toplevel().winfo_y()
        progress.geometry(f"{w}x{h}+{parent_x + 100}+{parent_y + 180}")

        tk.Label(
            progress,
            text="Connecting to MetaTrader 5...\nPlease make sure MT5 terminal is running.",
            font=("Segoe UI", 10),
            bg="#1e1e2e", fg="#cdd6f4",
            wraplength=280, justify="center",
            pady=15
        ).pack(fill="both", expand=True)

        result_err: list[str | None] = []

        def run_check():
            try:
                # mt5.initialize requires login to be int
                login_val = int(login_str)
                # Attempt to initialize and login
                if not mt5.initialize(login=login_val, password=password, server=server):
                    err_code, err_desc = mt5.last_error()
                    result_err.append(f"Initialization failed (Code {err_code}): {err_desc}\nMake sure MetaTrader 5 terminal is installed and active.")
                    return

                # Check account credentials check
                acc_info = mt5.account_info()
                if acc_info is None:
                    err_code, err_desc = mt5.last_error()
                    result_err.append(f"Credentials rejected by server (Code {err_code}): {err_desc}")
                else:
                    # Connection check successful!
                    result_err.append(None)
            except Exception as e:
                result_err.append(f"Verification error: {e}")
            finally:
                mt5.shutdown()
                try:
                    progress.destroy()
                except Exception:
                    pass

        t = threading.Thread(target=run_check, daemon=True)
        t.start()
        self.wait_window(progress)

        if result_err and result_err[0] is not None:
            return result_err[0]

        return None

    def collect(self) -> dict[str, str]:
        return {k: v.get().strip() for k, v in self._vars.items()}


class GroupsPage(_Page):
    title = "Signal Groups"
    subtitle = "Add the Telegram channels you want to copy signals from."

    def __init__(self, parent: tk.Widget) -> None:
        super().__init__(parent)
        self._groups: list[str] = []

        tk.Label(
            self,
            text="Type the exact channel name as it appears in Telegram, then click  Add.",
            font=("Segoe UI", 9),
            bg="#1e1e2e", fg="#6c7086",
            wraplength=460,
            justify="left",
        ).pack(anchor="w", padx=30, pady=(14, 6))

        # Input row
        row = tk.Frame(self, bg="#1e1e2e")
        row.pack(fill="x", padx=30)
        self._entry_var = tk.StringVar()
        entry = tk.Entry(
            row,
            textvariable=self._entry_var,
            font=("Segoe UI", 10),
            bg="#313244", fg="#cdd6f4",
            insertbackground="#cdd6f4",
            relief="flat", bd=6,
            width=38,
        )
        entry.pack(side="left", fill="x", expand=True, pady=2)
        entry.bind("<Return>", lambda _: self._add())
        tk.Button(
            row,
            text=" + Add ",
            font=("Segoe UI", 10, "bold"),
            bg="#89b4fa", fg="#1e1e2e",
            relief="flat", bd=0,
            cursor="hand2",
            command=self._add,
        ).pack(side="left", padx=(6, 0))

        # List frame
        list_frame = tk.Frame(self, bg="#1e1e2e")
        list_frame.pack(fill="both", expand=True, padx=30, pady=(8, 0))
        scrollbar = tk.Scrollbar(list_frame, orient="vertical")
        self._listbox = tk.Listbox(
            list_frame,
            font=("Segoe UI", 10),
            bg="#313244", fg="#cdd6f4",
            selectbackground="#89b4fa", selectforeground="#1e1e2e",
            relief="flat", bd=0,
            activestyle="none",
            yscrollcommand=scrollbar.set,
            height=6,
        )
        scrollbar.config(command=self._listbox.yview)
        scrollbar.pack(side="right", fill="y")
        self._listbox.pack(fill="both", expand=True)

        tk.Button(
            self,
            text=" ✕ Remove selected ",
            font=("Segoe UI", 9),
            bg="#f38ba8", fg="#1e1e2e",
            relief="flat", bd=0,
            cursor="hand2",
            command=self._remove,
        ).pack(anchor="e", padx=30, pady=(4, 0))

    def _add(self) -> None:
        name = self._entry_var.get().strip()
        if name and name not in self._groups:
            self._groups.append(name)
            self._listbox.insert(tk.END, name)
            self._entry_var.set("")

    def _remove(self) -> None:
        sel = self._listbox.curselection()
        if sel:
            idx = sel[0]
            self._groups.pop(idx)
            self._listbox.delete(idx)

    def validate(self) -> str | None:
        if not self._groups:
            return "Add at least one Telegram signal group"
        return None

    def collect(self) -> dict[str, str]:
        return {"telegram_sources": ",".join(self._groups)}


class AIPage(_Page):
    title = "AI Provider  (optional)"
    subtitle = "An AI key improves signal parsing accuracy. You can skip this."

    def __init__(self, parent: tk.Widget) -> None:
        super().__init__(parent)
        self._key_var = tk.StringVar()
        self._vol_var = tk.StringVar(value="0.01")

        tk.Label(
            self,
            text="OpenAI-compatible API Key",
            font=("Segoe UI", 10, "bold"),
            bg="#1e1e2e", fg="#cdd6f4",
        ).pack(anchor="w", padx=30, pady=(20, 0))
        tk.Entry(
            self,
            textvariable=self._key_var,
            show="●",
            font=("Consolas", 10),
            bg="#313244", fg="#cdd6f4",
            insertbackground="#cdd6f4",
            relief="flat", bd=6, width=50,
        ).pack(fill="x", padx=30, pady=2)
        tk.Label(
            self,
            text="Leave blank to use heuristic-only parsing (still works well for standard signals).",
            font=("Segoe UI", 9),
            bg="#1e1e2e", fg="#6c7086",
            wraplength=460, justify="left",
        ).pack(anchor="w", padx=30)

        tk.Label(
            self,
            text="Default Trade Volume (lots)",
            font=("Segoe UI", 10, "bold"),
            bg="#1e1e2e", fg="#cdd6f4",
        ).pack(anchor="w", padx=30, pady=(20, 0))
        tk.Entry(
            self,
            textvariable=self._vol_var,
            font=("Consolas", 10),
            bg="#313244", fg="#cdd6f4",
            insertbackground="#cdd6f4",
            relief="flat", bd=6, width=12,
        ).pack(anchor="w", padx=30, pady=2)
        tk.Label(
            self,
            text="e.g. 0.01 = micro lot. Adjust to your account size and risk tolerance.",
            font=("Segoe UI", 9),
            bg="#1e1e2e", fg="#6c7086",
        ).pack(anchor="w", padx=30)

    def validate(self) -> str | None:
        vol = self._vol_var.get().strip()
        try:
            if float(vol) <= 0:
                raise ValueError
        except ValueError:
            return "Default Volume must be a positive number (e.g. 0.01)"
        return None

    def collect(self) -> dict[str, str]:
        return {
            "openai_api_key": self._key_var.get().strip(),
            "default_volume": self._vol_var.get().strip(),
        }


class FinishPage(_Page):
    title = "Ready to Launch"
    subtitle = "Your configuration has been saved."

    def __init__(self, parent: tk.Widget, env_path: Path | None = None) -> None:
        super().__init__(parent)
        self._env_path = env_path or Path("(not yet written)")

        self._status_var = tk.StringVar(value="")
        self._path_var = tk.StringVar(value=str(self._env_path))

        tk.Label(
            self,
            text="✔  Configuration saved to:",
            font=("Segoe UI", 11, "bold"),
            bg="#1e1e2e", fg="#a6e3a1",
        ).pack(anchor="w", padx=30, pady=(24, 2))
        tk.Label(
            self,
            textvariable=self._path_var,
            font=("Consolas", 9),
            bg="#1e1e2e", fg="#89b4fa",
            wraplength=460, justify="left",
        ).pack(anchor="w", padx=30)

        tk.Label(
            self,
            text="\nNext steps:",
            font=("Segoe UI", 11, "bold"),
            bg="#1e1e2e", fg="#cdd6f4",
        ).pack(anchor="w", padx=30)
        steps = [
            "1. Click  'Telegram Login'  below to authorise the app (one-time).",
            "2. Open MT5 and attach the  TelegramSignalCopierEA  to any chart.",
            "3. Click  'Start Listener'  to begin copying signals.",
        ]
        for s in steps:
            tk.Label(
                self,
                text=s,
                font=("Segoe UI", 10),
                bg="#1e1e2e", fg="#cdd6f4",
                anchor="w", wraplength=460, justify="left",
            ).pack(anchor="w", padx=30, pady=2)

        tk.Label(
            self,
            textvariable=self._status_var,
            font=("Segoe UI", 10, "italic"),
            bg="#1e1e2e", fg="#f9e2af",
            wraplength=460, justify="left",
        ).pack(anchor="w", padx=30, pady=(12, 0))

        btn_row = tk.Frame(self, bg="#1e1e2e")
        btn_row.pack(anchor="w", padx=30, pady=(18, 0))
        self._login_btn = tk.Button(
            btn_row,
            text=" Telegram Login ",
            font=("Segoe UI", 11, "bold"),
            bg="#89b4fa", fg="#1e1e2e",
            relief="flat", bd=0,
            cursor="hand2",
            command=self._run_login,
        )
        self._login_btn.pack(side="left", padx=(0, 10))
        self._listen_btn = tk.Button(
            btn_row,
            text=" Start Listener ",
            font=("Segoe UI", 11, "bold"),
            bg="#a6e3a1", fg="#1e1e2e",
            relief="flat", bd=0,
            cursor="hand2",
            command=self._run_listener,
        )
        self._listen_btn.pack(side="left")

    def update_path(self, path: Path) -> None:
        self._env_path = path
        self._path_var.set(str(path))

    def _exe(self) -> str:
        """Return the executable path (frozen or venv python)."""
        if getattr(sys, "frozen", False):
            return sys.executable
        return sys.executable

    def _run_login(self) -> None:
        self._status_var.set("⏳  Opening Telegram login… check the terminal window.")
        self._login_btn.config(state="disabled")

        def _do():
            try:
                exe = self._exe()
                if getattr(sys, "frozen", False):
                    args = [exe, "login"]
                else:
                    args = [exe, "-m", "telegram_signal_copier.main", "login"]
                subprocess.Popen(args, creationflags=subprocess.CREATE_NEW_CONSOLE if os.name == "nt" else 0)
                self._status_var.set("✔  Login process launched in a new window.")
            except Exception as exc:
                self._status_var.set(f"✖  Failed to launch: {exc}")
            finally:
                self._login_btn.config(state="normal")

        threading.Thread(target=_do, daemon=True).start()

    def _run_listener(self) -> None:
        self._status_var.set("⏳  Starting listener…")
        self._listen_btn.config(state="disabled")

        def _do():
            try:
                exe = self._exe()
                if getattr(sys, "frozen", False):
                    args = [exe, "listen"]
                else:
                    args = [exe, "-m", "telegram_signal_copier.main", "listen"]
                subprocess.Popen(args, creationflags=subprocess.CREATE_NEW_CONSOLE if os.name == "nt" else 0)
                self._status_var.set("✔  Listener started in a new window.")
            except Exception as exc:
                self._status_var.set(f"✖  Failed: {exc}")
            finally:
                self._listen_btn.config(state="normal")

        threading.Thread(target=_do, daemon=True).start()


# ---------------------------------------------------------------------------
# Wizard shell
# ---------------------------------------------------------------------------

class SetupWizard(tk.Tk):
    _TITLE_BG = "#181825"
    _PAGE_BG  = "#1e1e2e"
    _BTN_BG   = "#313244"
    _ACCENT   = "#89b4fa"

    def __init__(self) -> None:
        super().__init__()
        self.title("Telegram Signal Copier — Setup")
        self.resizable(False, False)
        self.configure(bg=self._TITLE_BG)
        self._center(520, 560)

        self._collected: dict[str, str] = {}
        self._pages: list[_Page] = []
        self._current = 0
        self._env_path: Path | None = None

        self._build_header()
        self._build_body()
        self._build_footer()

        # Build pages (finish page keeps a reference so we can update its path)
        self._finish_page = FinishPage(self._body)
        pages_list: list[_Page] = [
            WelcomePage(self._body),
            TelegramPage(self._body),
            MT5Page(self._body),
            GroupsPage(self._body),
            AIPage(self._body),
            self._finish_page,
        ]
        self._pages = pages_list
        self._show_page(0)

    def _center(self, w: int, h: int) -> None:
        self.update_idletasks()
        x = (self.winfo_screenwidth() - w) // 2
        y = (self.winfo_screenheight() - h) // 2
        self.geometry(f"{w}x{h}+{x}+{y}")

    def _build_header(self) -> None:
        hdr = tk.Frame(self, bg=self._TITLE_BG, height=64)
        hdr.pack(fill="x")
        hdr.pack_propagate(False)
        self._hdr_title = tk.Label(
            hdr,
            text="",
            font=("Segoe UI", 13, "bold"),
            bg=self._TITLE_BG, fg="#cdd6f4",
        )
        self._hdr_title.pack(side="left", padx=20, pady=8)
        self._hdr_sub = tk.Label(
            hdr,
            text="",
            font=("Segoe UI", 9),
            bg=self._TITLE_BG, fg="#6c7086",
        )
        self._hdr_sub.pack(side="left", padx=0, pady=8)

        # Step indicators
        self._step_frame = tk.Frame(self, bg=self._TITLE_BG)
        self._step_frame.pack(fill="x", padx=20)
        self._step_labels: list[tk.Label] = []
        page_names = ["Welcome", "Telegram", "MT5", "Groups", "AI / Volume", "Finish"]
        for i, name in enumerate(page_names):
            lbl = tk.Label(
                self._step_frame,
                text=f"{'●' if i == 0 else '○'} {name}",
                font=("Segoe UI", 8),
                bg=self._TITLE_BG,
                fg=self._ACCENT if i == 0 else "#45475a",
            )
            lbl.pack(side="left", padx=6, pady=2)
            self._step_labels.append(lbl)

        ttk.Separator(self, orient="horizontal").pack(fill="x")

    def _build_body(self) -> None:
        self._body = tk.Frame(self, bg=self._PAGE_BG)
        self._body.pack(fill="both", expand=True)

    def _build_footer(self) -> None:
        ttk.Separator(self, orient="horizontal").pack(fill="x")
        footer = tk.Frame(self, bg=self._TITLE_BG, height=52)
        footer.pack(fill="x")
        footer.pack_propagate(False)

        self._btn_next = tk.Button(
            footer,
            text="  Next  ›",
            font=("Segoe UI", 10, "bold"),
            bg=self._ACCENT, fg="#1e1e2e",
            relief="flat", bd=0,
            cursor="hand2",
            command=self._on_next,
        )
        self._btn_next.pack(side="right", padx=16, pady=10)

        self._btn_back = tk.Button(
            footer,
            text="‹  Back  ",
            font=("Segoe UI", 10),
            bg=self._BTN_BG, fg="#cdd6f4",
            relief="flat", bd=0,
            cursor="hand2",
            command=self._on_back,
        )
        self._btn_back.pack(side="right", padx=4, pady=10)

        self._step_info = tk.Label(
            footer,
            text="",
            font=("Segoe UI", 9),
            bg=self._TITLE_BG, fg="#6c7086",
        )
        self._step_info.pack(side="left", padx=16)

    def _show_page(self, idx: int) -> None:
        # Hide current page
        if self._pages:
            for p in self._pages:
                p.pack_forget()

        page = self._pages[idx]
        page.pack(fill="both", expand=True)
        self._current = idx

        # Update header
        self._hdr_title.config(text=page.title)
        self._hdr_sub.config(text=page.subtitle)

        # Update step indicators
        for i, lbl in enumerate(self._step_labels):
            name = lbl.cget("text").split(" ", 1)[1]
            if i < idx:
                lbl.config(text=f"✔ {name}", fg="#a6e3a1")
            elif i == idx:
                lbl.config(text=f"● {name}", fg=self._ACCENT)
            else:
                lbl.config(text=f"○ {name}", fg="#45475a")

        # Update buttons
        self._btn_back.config(state="normal" if idx > 0 else "disabled")
        total = len(self._pages)
        self._step_info.config(text=f"Step {idx + 1} of {total}")

        is_last = idx == total - 1
        self._btn_next.config(
            text="  Close  " if is_last else "  Next  ›",
            bg="#f38ba8" if is_last else self._ACCENT,
        )

    def _on_next(self) -> None:
        page = self._pages[self._current]
        err = page.validate()
        if err:
            messagebox.showerror("Validation Error", err, parent=self)
            return

        self._collected.update(page.collect())

        next_idx = self._current + 1
        if next_idx >= len(self._pages):
            self.destroy()
            return

        # Before showing finish page: write .env
        if next_idx == len(self._pages) - 1:
            try:
                self._env_path = _write_env(self._collected)
                self._finish_page.update_path(self._env_path)
            except Exception as exc:
                messagebox.showerror("Write Error", f"Could not save .env:\n{exc}", parent=self)
                return

        self._show_page(next_idx)

    def _on_back(self) -> None:
        if self._current > 0:
            self._show_page(self._current - 1)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _open_url(url: str) -> None:
    import webbrowser
    webbrowser.open(url)


# ---------------------------------------------------------------------------
# Launcher window (shown when .env already exists — double-click EXE)
# ---------------------------------------------------------------------------

class _LauncherWindow(tk.Tk):
    """Compact launcher shown when config already exists."""

    def __init__(self) -> None:
        super().__init__()
        self.title("Telegram Signal Copier")
        self.resizable(False, False)
        self.configure(bg="#181825")
        self._status_var = tk.StringVar(value="")
        self._center(420, 300)
        self._build()

    def _center(self, w: int, h: int) -> None:
        self.update_idletasks()
        x = (self.winfo_screenwidth() - w) // 2
        y = (self.winfo_screenheight() - h) // 2
        self.geometry(f"{w}x{h}+{x}+{y}")

    def _build(self) -> None:
        # Title
        hdr = tk.Frame(self, bg="#181825")
        hdr.pack(fill="x", pady=(20, 4))
        tk.Label(
            hdr,
            text="Telegram Signal Copier",
            font=("Segoe UI", 15, "bold"),
            bg="#181825", fg="#cdd6f4",
        ).pack()
        tk.Label(
            hdr,
            text="✔  Configuration found",
            font=("Segoe UI", 10),
            bg="#181825", fg="#a6e3a1",
        ).pack(pady=(2, 0))

        ttk.Separator(self, orient="horizontal").pack(fill="x", pady=10)

        # Buttons
        btn_frame = tk.Frame(self, bg="#181825")
        btn_frame.pack(pady=8)
        tk.Button(
            btn_frame,
            text="  Telegram Login  ",
            font=("Segoe UI", 11, "bold"),
            bg="#89b4fa", fg="#1e1e2e",
            relief="flat", bd=0, cursor="hand2",
            command=self._run_login,
            width=18,
        ).pack(pady=6)
        tk.Button(
            btn_frame,
            text="  Start Listener  ",
            font=("Segoe UI", 11, "bold"),
            bg="#a6e3a1", fg="#1e1e2e",
            relief="flat", bd=0, cursor="hand2",
            command=self._run_listener,
            width=18,
        ).pack(pady=6)
        tk.Button(
            btn_frame,
            text="  Reconfigure  ",
            font=("Segoe UI", 10),
            bg="#313244", fg="#cdd6f4",
            relief="flat", bd=0, cursor="hand2",
            command=self._reconfigure,
            width=18,
        ).pack(pady=6)

        # Status label
        tk.Label(
            self,
            textvariable=self._status_var,
            font=("Segoe UI", 9, "italic"),
            bg="#181825", fg="#f9e2af",
            wraplength=380,
        ).pack(pady=(4, 0))

    def _exe(self) -> str:
        return sys.executable

    def _run_login(self) -> None:
        self._status_var.set("⏳  Opening Telegram login in a new window…")
        def _do():
            try:
                exe = self._exe()
                args = [exe, "login"] if getattr(sys, "frozen", False) else [exe, "-m", "telegram_signal_copier.main", "login"]
                subprocess.Popen(args, creationflags=subprocess.CREATE_NEW_CONSOLE if os.name == "nt" else 0)
                self._status_var.set("✔  Login window opened.")
            except Exception as exc:
                self._status_var.set(f"✖  {exc}")
        threading.Thread(target=_do, daemon=True).start()

    def _run_listener(self) -> None:
        self._status_var.set("⏳  Starting listener…")
        def _do():
            try:
                exe = self._exe()
                args = [exe, "listen"] if getattr(sys, "frozen", False) else [exe, "-m", "telegram_signal_copier.main", "listen"]
                subprocess.Popen(args, creationflags=subprocess.CREATE_NEW_CONSOLE if os.name == "nt" else 0)
                self._status_var.set("✔  Listener started in a new window.")
            except Exception as exc:
                self._status_var.set(f"✖  {exc}")
        threading.Thread(target=_do, daemon=True).start()

    def _reconfigure(self) -> None:
        self.destroy()
        run_wizard()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def run_wizard() -> None:
    """Launch the full setup wizard (blocking until closed)."""
    app = SetupWizard()
    app.mainloop()


def run_launcher() -> None:
    """Show the compact launcher (when .env already exists)."""
    app = _LauncherWindow()
    app.mainloop()


if __name__ == "__main__":
    run_wizard()
