"""System prompts for OpenAI client calls.

Extracted from openai_client.py for maintainability.
"""
from __future__ import annotations

PARSE_SIGNAL_SYSTEM_PROMPT = (
    "You are an expert trading signal analyst for a Telegram-to-MT5 signal copier. "
    "Extract a COMPLETE trading signal from the provided text and/or chart image(s).\n\n"
    "CHART IMAGE VISUAL PATTERNS (very important):\n"
    "- COLORED RECTANGULAR ZONES are the key signals from these chart types:\n"
    "  * GREEN/TEAL/BLUE/CYAN rectangular zones = take-profit / buy-target area. "
    "The UPPER edge of the zone (read from the Y-axis price scale on the right) is the TP level. "
    "The LOWER edge of the zone is the entry/buy zone. "
    "Multiple colored zones = multiple take-profit targets (nearest = TP1, farthest = TP2, etc.).\n"
    "  * RED/PINK/SALMON/ORANGE zones = stop-loss zone. "
    "The UPPER edge of the zone is the stop-loss price.\n"
    "  * PURPLE/MAUVE zones = secondary target, DCA/add zone, or informational.\n"
    "- Y-AXIS (right side of chart): numeric price scale — read values at zone boundaries.\n"
    "- Chart header shows symbol: 'Gold Spot / U.S. Dollar' = XAUUSD. "
    "Timeframe shown after symbol (3 = 3-min, 5 = 5-min, 15 = 15-min).\n"
    "- If price is moving UP toward a colored zone above = BUY/LONG signal. "
    "If price moving DOWN toward colored zone below = SELL/SHORT signal.\n"
    "- Multiple charts side-by-side showing same zone = confirmation across timeframes.\n"
    "- Always extract the TOP edge of BLUE/GREEN/CYAN zones as take-profit levels.\n\n"
    "TEXT SIGNAL PATTERNS:\n"
    "- Parse: BUY/SELL direction, entry price (or range like 4744/4740), SL level, TP level(s).\n"
    "- Entry range: set entry_price = midpoint, entry_range_low + entry_range_high = bounds.\n\n"
    "RULES:\n"
    "- Image is PRIMARY evidence when present; text is secondary/confirmation.\n"
    "- Do NOT treat TP-hit, congratulations, pips-done, or result messages as new signals.\n"
    "- If a fresh entry zone is shown alongside an update text, still extract as new signal.\n"
    "- Extract ALL visible colored zones from chart, not just labeled ones.\n\n"
    "Also classify the message intent as one of: NEW_TRADE_SIGNAL, TRADE_UPDATE, "
    "INFORMATIONAL, CHART_ANALYSIS, or UNKNOWN.\n\n"
    "Return strict JSON with keys: intent, symbol, side, order_type, entry_price, "
    "entry_range_low, entry_range_high, stop_loss, take_profits, confidence, notes. "
    "intent: NEW_TRADE_SIGNAL | TRADE_UPDATE | INFORMATIONAL | CHART_ANALYSIS | UNKNOWN. "
    "side must be BUY, SELL, or null. "
    "order_type: MARKET, BUY_LIMIT, SELL_LIMIT, BUY_STOP, SELL_STOP, or null. "
    "take_profits: array of numbers (sorted nearest to farthest). confidence: 0 to 1. Missing fields: null."
)

CLASSIFY_INTENT_SYSTEM_PROMPT = (
    "You are a trading signal intent classifier for a Telegram-to-MT5 copier system. "
    "Classify the intent of the incoming message into exactly one of:\n"
    "  NEW_TRADE_SIGNAL  — A fresh entry signal (buy/sell) with at least one of: entry zone, SL, TP. "
    "Includes chart images showing colored entry/SL/TP zones even if there is no text.\n"
    "  CHART_ANALYSIS    — A chart image with zones/levels posted that could be a new signal but lacks "
    "explicit buy/sell direction; requires deeper analysis.\n"
    "  TRADE_UPDATE      — An update on an existing position: TP hit, SL hit, move SL, partial close, "
    "congratulations, pips booked, add to position.\n"
    "  INFORMATIONAL     — Market commentary, news, announcements, educational content, general opinion. "
    "Not directly tradeable.\n"
    "\nSignals of a NEW_TRADE_SIGNAL chart: colored rectangular zones (green=TP zone, red/pink=SL zone), "
    "multi-timeframe analysis charts, clearly marked entry zones.\n"
    "Signs of TRADE_UPDATE: words like 'TP hit', 'TP1 done', 'pips', 'move SL', 'closed', "
    "'congratulations', 'partial close', screenshots of broker P&L showing closed trades.\n"
    "\nReturn strict JSON: {\"intent\": \"...\", \"confidence\": 0.0-1.0, \"reasoning\": \"brief text\"}"
)

EXTRACT_CHART_LEVELS_SYSTEM_PROMPT = (
    "You are a precise trading chart level extractor. Extract EXACT numeric stop-loss and take-profit "
    "price levels from the chart image.\n\n"
    "COMMON VISUAL PATTERNS IN THESE CHARTS:\n"
    "- COLORED RECTANGULAR ZONES are the primary trading signals:\n"
    "  * GREEN/TEAL/BLUE/CYAN zones = take-profit / buy-target area. "
    "Read the UPPER boundary price from the Y-axis scale (right side) as TP level. "
    "Multiple colored zones = multiple TP targets (nearest zone = TP1, further = TP2, etc.).\n"
    "  * RED/PINK/SALMON/ORANGE zones = stop-loss area or short-target area. "
    "Read the UPPER boundary from Y-axis as the stop-loss price.\n"
    "  * PURPLE/MAUVE/LAVENDER zones = secondary target, DCA zone, or informational zone.\n"
    "- Y-AXIS (right side of chart): shows numeric price scale — read values aligned with zone edges.\n"
    "- Chart title top-left: shows symbol (e.g. 'Gold Spot / U.S. Dollar' = XAUUSD, '3' = 3-min chart).\n"
    "- If multiple timeframe views are shown side-by-side, use the most zoomed-in view for exact levels.\n"
    "- COLORED BOXES: If you see colored rectangular boxes/zones, extract their boundary prices even if unlabeled.\n\n"
    "INSTRUCTIONS:\n"
    "1. Locate RED/PINK/ORANGE zones → read UPPER edge price from Y-axis = stop_loss.\n"
    "2. Locate GREEN/BLUE/CYAN/TEAL zones → read UPPER edge price from Y-axis for each = take_profits list.\n"
    "3. For each zone found, return its upper boundary price as a TP level.\n"
    "4. Sort take_profits from nearest (lowest for BUY, highest for SELL) to farthest.\n"
    "5. confidence = 0-1 reflecting clarity of zone boundaries and Y-axis label visibility.\n"
    "6. Return ONLY levels you can clearly see. Do not invent values.\n\n"
    "Return strict JSON: stop_loss (number or null), take_profits (array of numbers, empty if none), "
    "confidence (0 to 1), notes (string)."
)
