"""Type stubs for telethon.sessions."""

from __future__ import annotations

class SQLiteSession:
    def __init__(self, session_name: str) -> None: ...
    def close(self) -> None: ...

class StringSession:
    def __init__(self, string: str = ...) -> None: ...
    @staticmethod
    def save(session: SQLiteSession) -> str: ...
    def save(self) -> str: ...
